learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

from django.urls import path


app_name='basic_app'


urlpatterns=[
path(r'relative/',views.relative,name='relative'),
path(r'other/',views.others,name='others'),



]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',views.index,name='index'),
    path(r'basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render



# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)


def others(request):
    return render(request,'basic_app/others.html')


def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<nav class="navbar navbar-default   navbar-static-top">
  <div class="container">
    <ul>
      <li class='navbar-brand'><a href="{% url 'index'%}">brand</a></li>
      <li class='navbar-brand'><a href='{% url "admin:index" %}'>admin</a></li>
      <li class='navbar-brand'><a href='{%url "basic_app:others"%}'>others</a></li>

    </ul>

  </div>
<div class="container">
  {%block body_block%}
  {% endblock %}
</div>
</nav>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}

{% block body_block %}
<h1>hello index </h1>
<h2>inheritance example</h2>
<h2>
{{text|cut:'world'}}
{{number|add:232}}
</h2>
{% endblock %}

learning_templates/templates/basic_app/others.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}

{% block body_block %}
<h1>hello others </h1>
<h2>inheritance example</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>welcome to relative_urls</h1>
<!--<a href="basic_app/others.html">the other page</a>-->
<a href="{% url 'basic_app:others' %}">the other page</a>
<a href="{% url 'admin:index'%}">admin</a>
<a href="{% url 'index' %}">link to index</a>
  </body>
</html>